apply plugin: 'com.android.application'

android {
    namespace 'com.liveperson.sample.app'

    compileSdk 37

    defaultConfig {
        applicationId "com.liveperson.sample.app"
        minSdkVersion 21
        targetSdkVersion 37
        versionCode 5280
        versionName "5.28.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig = true
        viewBinding true
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.firebase:firebase-messaging:24.1.0'
//    implementation "com.huawei.hms:push:5.0.4.302" // Huawei push notification
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.gridlayout:gridlayout:1.1.0'
    testImplementation "junit:junit:4.13.2"

    implementation 'com.liveperson.android:lp_messaging_sdk:5.28.0'
}

apply plugin: 'com.google.gms.google-services'
