android.nonFinalResIds=false
android.nonTransitiveRClass=false
android.useAndroidX=true
org.gradle.jvmargs=-Xmx4608M
#org.gradle.unsafe.configuration-cache=true
org.gradle.configuration-cache=false
#AGP manages the Kotlin version internally. AGP 9.1.1 bundles KGP 2.2.10. Setting this explicitly tells AGP to use it.
android.builtInKotlin=true
android.enableAppCompileTimeRClass=false
